### necessary consts
wl = [0.70931715, 0.713607]

### p4p file location
p4p_folder = "D:/data/p4p"
p4p_file = "LaB6.p4p"

### lattice param correction
a = 4.156916

### sfrm files location
sfrm_folder = "td"
sfrm_files =  [ "9.sfrm", "10.sfrm" ]


### checkboxes
correct_lattice = true
drawing = false
check = false
shift_corr = true
logging = false


### suppose params
hkl_max = 10
tth_min = 90.0
tth_max = 100.0
d = 128.533
om_scan_range = 4.0


### eval params
#peaks = [[389, 503], [402, 503]]
x_lims = [360, 420]
y_lims = [490, 520]
xc = 395.50
yc = 504.13
sigma = 2.0
noise = 200


### suppose consts
chi = 54.7112
tth_lim = 100.0
tth_om_delta = 43.22


### eval consts
rows = 1024
cols = 786
px_size = 0.135
