### necessary consts
wl = [0.70931715, 0.713607]
chi = 54.7112

### lattice param correction
a = 5.43093

res_folder = "res"

### p4p file location
p4p_file = "D:\\data\\p4p\\Cringe.p4p"

### cif file location
cif_file = "D:\\data\\cif\\Si.cif"

### sfrm files location
sfrm_folder = "D:\\data\\samples\\Si_small"


### checkboxes
correct_lattice = false

### suppose params
hkl_max = 10
tth_min = 30.0
tth_max = 90.0
d = 128.533
om_scan_range = 4.0


### eval params
x_lims = [360, 420]
y_lims = [490, 520]
xc = 395.50
yc = 504.13
sigma = 2.0
threshold = 1e5


### suppose consts
tth_lim = 100.0
tth_om_delta = 43.22


### eval consts
rows = 1024
cols = 768
px_size = 0.135
